spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jarvislueng/springLearn/
          search-paths: config-repo
      label: master
server:
  port: 8888